# Generated by Django 5.2.8 on 2025-11-27 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the vlog post', max_length=200)),
                ('video_url', models.URLField(help_text='URL of the vlog video')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the vlog')),
                ('published_date', models.DateTimeField(auto_now_add=True, help_text='Date and time when the vlog was published')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags for the vlog', max_length=200)),
                ('category', models.CharField(choices=[('travel', 'Travel'), ('tech', 'Tech'), ('lifestyle', 'Lifestyle'), ('gaming', 'Gaming'), ('food', 'Food'), ('education', 'Education')], help_text='Category of the vlog post', max_length=50)),
                ('author', models.ForeignKey(help_text='User who created the vlog', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
