# Generated by Django 5.2.8 on 2025-11-28 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the vlog', max_length=200)),
                ('video_url', models.URLField(help_text='URL of the vlog video')),
                ('description', models.TextField(blank=True, help_text='Description of the vlog')),
                ('published_date', models.DateTimeField(auto_now_add=True, help_text='Date published')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=200)),
                ('author', models.ForeignKey(help_text='Author of the vlog', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, help_text='Category of the vlog', null=True, on_delete=django.db.models.deletion.SET_NULL, to='vlogs.category')),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
