# Generated by Django 5.2.8 on 2025-11-27 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlogs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlogpost',
            name='author',
            field=models.ForeignKey(help_text='Author of the vlog', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vlogpost',
            name='category',
            field=models.CharField(choices=[('travel', 'Travel'), ('tech', 'Tech'), ('lifestyle', 'Lifestyle'), ('gaming', 'Gaming'), ('food', 'Food'), ('education', 'Education')], help_text='Category of the vlog', max_length=50),
        ),
        migrations.AlterField(
            model_name='vlogpost',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the vlog'),
        ),
        migrations.AlterField(
            model_name='vlogpost',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Date published'),
        ),
        migrations.AlterField(
            model_name='vlogpost',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags', max_length=200),
        ),
        migrations.AlterField(
            model_name='vlogpost',
            name='title',
            field=models.CharField(help_text='Title of the vlog', max_length=200),
        ),
    ]
